---
- name: Create a sudo user and setup SSH
  hosts: test  # Replace with your target host or group
  become: true  # Become root to run the tasks
  vars:
    username: "kaushik_dwivedi"
    user_password: "password"  # Replace with the desired password for the user

  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present

    - name: Add the user to the sudoers group
      user:
        name: "{{ username }}"
        group: sudo
        append: yes

    - name: Create .ssh directory for the user
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
