---
- name: Create a sudo user and setup SSH
  hosts: test  
  become: true  
  vars:
    username: "kaushik_dwivedi"
    user_password: "12345"  

  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present

    - name: Add the user to the sudoers group
      user:
        name: "{{ username }}"
        groups: sudo  # Specify the groups parameter
        append: yes

    - name: Create .ssh directory for the user
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
