- name: Generate SSH Key Pair
  hosts: test  
  become: yes  
  tasks:
    - name: Ensure the SSH key pair is generated
      command: ssh-keygen -t rsa -b 4096 -C "kaushik.dwivedi@sarvagram.com" -f /home/ubuntu/.ssh/id_rsa -N ""
      args:
        creates: /home/ubuntu/.ssh/id_rsa

    - name: Read the public key
      slurp:
        src: /home/ubuntu/.ssh/id_rsa.pub
      register: public_key_data

    - name: Debug public_key_data
      debug:
        var: public_key_data

    - name: Create authorized_keys file
      file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Add public key to authorized_keys
      copy:
        content: "{{ public_key_data['content'] | b64decode }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
