---
- name: Create a sudo user and setup SSH
  hosts: test  
  become: true  
  vars:
    username: "demo_user"
    user_password: "12345"  

  tasks:
    - name: Create a new user with home directory
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
        create_home: yes  # Ensure home directory is created
        shell: /bin/bash  # Set the shell to bash

    - name: Add the user to the sudoers group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Ensure .ssh directory for the user exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Create authorized_keys file
      file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Add public key to authorized_keys
      copy:
        content: "{{ public_key_data['content'] | b64decode }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

  
