---
- name: Generate SSH Key Pair
  hosts: test  # Replace with your target host or group
  become: yes         # Use 'become' if you need elevated privileges
  tasks:
    - name: Ensure the SSH key pair is generated
      command: ssh-keygen -t rsa -b 4096 -C "kaushik.dwivedi@sarvagram.com" -f /home/ubuntu/.ssh/id_rsa -N ""  # Change path if needed
      args:
        creates: /home/ubuntu/.ssh/id_rsa

